[config.wallpaper]
set = true
command = "awww img --transition-type wave {{ image }}"

[templates.waybar]
input_path = '~/.config/matugen/templates/colors.css'
output_path = '~/.config/waybar/colors.css'
post_hook = "pkill -SIGUSR2 waybar"

[templates.walker]
input_path = '~/.config/matugen/templates/colors.css'
output_path = '~/.config/walker/themes/matugen/colors.css'

[templates.hyprland]
input_path = '~/.config/matugen/templates/hyprland-colors.conf'
output_path = '~/.config/hypr/colors.conf'

[templates.mako]
input_path = '~/.config/matugen/templates/mako'
output_path = '~/.config/mako/mako-colors'
post_hook = 'makoctl reload'

[templates.brave]
input_path = "~/.config/matugen/templates/brave"
output_path = "/tmp/brave_hex"
post_hook = "~/.config/matugen/reload-theme.sh"

[templates.ghostty]
input_path = "~/.config/matugen/templates/ghostty"
output_path = "~/.config/ghostty/themes/Matugen"
post_hook = 'pkill -SIGUSR2 ghostty'

[templates.gtkicon]
input_path = "~/.config/matugen/templates/hue"
output_path = "/tmp/matugen_hue"
post_hook = "~/.config/matugen/set-icon-theme.sh"

[templates.gtk3]
input_path = "~/.config/matugen/templates/gtk-colors.css"
output_path = '~/.config/gtk-3.0/colors.css'
post_hook = 'gsettings set org.gnome.desktop.interface gtk-theme ""; gsettings set org.gnome.desktop.interface gtk-theme adw-gtk3-{{mode}}'

[templates.gtk4]
input_path = "~/.config/matugen/templates/gtk-colors.css"
output_path = '~/.config/gtk-4.0/colors.css'